class Autogenerated {
  int? itemPrice;
  int? taxPrice;
  int? shippingPrice;
  int? totalPrice;
  List<OrderItems>? orderItems;
  ShippingInfo? shippingInfo;
  PaymentInfo? paymentInfo;

  Autogenerated(
      {this.itemPrice,
      this.taxPrice,
      this.shippingPrice,
      this.totalPrice,
      this.orderItems,
      this.shippingInfo,
      this.paymentInfo});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    itemPrice = json['itemPrice'];
    taxPrice = json['taxPrice'];
    shippingPrice = json['shippingPrice'];
    totalPrice = json['totalPrice'];
    if (json['orderItems'] != null) {
      orderItems = <OrderItems>[];
      json['orderItems'].forEach((v) {
        orderItems!.add(new OrderItems.fromJson(v));
      });
    }
    shippingInfo = json['shippingInfo'] != null
        ? new ShippingInfo.fromJson(json['shippingInfo'])
        : null;
    paymentInfo = json['paymentInfo'] != null
        ? new PaymentInfo.fromJson(json['paymentInfo'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['itemPrice'] = this.itemPrice;
    data['taxPrice'] = this.taxPrice;
    data['shippingPrice'] = this.shippingPrice;
    data['totalPrice'] = this.totalPrice;
    if (this.orderItems != null) {
      data['orderItems'] = this.orderItems!.map((v) => v.toJson()).toList();
    }
    if (this.shippingInfo != null) {
      data['shippingInfo'] = this.shippingInfo!.toJson();
    }
    if (this.paymentInfo != null) {
      data['paymentInfo'] = this.paymentInfo!.toJson();
    }
    return data;
  }
}

class OrderItems {
  String? product;
  String? name;
  int? price;
  String? image;
  int? quantity;

  OrderItems({this.product, this.name, this.price, this.image, this.quantity});

  OrderItems.fromJson(Map<String, dynamic> json) {
    product = json['product'];
    name = json['name'];
    price = json['price'];
    image = json['image'];
    quantity = json['quantity'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['product'] = this.product;
    data['name'] = this.name;
    data['price'] = this.price;
    data['image'] = this.image;
    data['quantity'] = this.quantity;
    return data;
  }
}

class ShippingInfo {
  String? address;
  String? city;
  String? state;
  String? country;
  int? pinCode;
  String? phoneNo;

  ShippingInfo(
      {this.address,
      this.city,
      this.state,
      this.country,
      this.pinCode,
      this.phoneNo});

  ShippingInfo.fromJson(Map<String, dynamic> json) {
    address = json['address'];
    city = json['city'];
    state = json['state'];
    country = json['country'];
    pinCode = json['pinCode'];
    phoneNo = json['phoneNo'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['address'] = this.address;
    data['city'] = this.city;
    data['state'] = this.state;
    data['country'] = this.country;
    data['pinCode'] = this.pinCode;
    data['phoneNo'] = this.phoneNo;
    return data;
  }
}

class PaymentInfo {
  String? id;
  String? status;

  PaymentInfo({this.id, this.status});

  PaymentInfo.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    status = json['status'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['status'] = this.status;
    return data;
  }
}
